-- Criação da tabela Setores
CREATE TABLE Setores (
    setor_id NUMBER CONSTRAINT pk_setores PRIMARY KEY,
    nome VARCHAR2(100) CONSTRAINT nn_nome_setor NOT NULL
);

-- Criação da tabela Trilhas de Treinamento
CREATE TABLE Trilhas_Treinamento (
    trilha_id NUMBER CONSTRAINT pk_trilhas PRIMARY KEY,
    nome VARCHAR2(100) CONSTRAINT nn_nome_trilha NOT NULL,
    setor_id NUMBER,
    CONSTRAINT fk_setor_trilha FOREIGN KEY (setor_id) REFERENCES Setores(setor_id) ON DELETE CASCADE
);

-- Criação da tabela Conteúdos
CREATE TABLE Conteudos (
    conteudo_id NUMBER CONSTRAINT pk_conteudos PRIMARY KEY,
    titulo VARCHAR2(100) CONSTRAINT nn_titulo_conteudo NOT NULL,
    descricao VARCHAR2(255)
);

-- Criação da tabela de relacionamento Conteúdos_Trilhas
CREATE TABLE Conteudos_Trilhas (
    conteudo_id NUMBER,
    trilha_id NUMBER,
    PRIMARY KEY (conteudo_id, trilha_id),
    CONSTRAINT fk_conteudo_trilha FOREIGN KEY (conteudo_id) REFERENCES Conteudos(conteudo_id) ON DELETE CASCADE,
    CONSTRAINT fk_trilha_conteudo FOREIGN KEY (trilha_id) REFERENCES Trilhas_Treinamento(trilha_id) ON DELETE CASCADE
);

-- Criação da tabela Atividades
CREATE TABLE Atividades (
    atividade_id NUMBER CONSTRAINT pk_atividades PRIMARY KEY,
    descricao VARCHAR2(255) CONSTRAINT nn_descricao_atividade NOT NULL,
    conteudo_id NUMBER,
    CONSTRAINT fk_conteudo_atividade FOREIGN KEY (conteudo_id) REFERENCES Conteudos(conteudo_id) ON DELETE CASCADE
);

-- Criação da tabela Usuários
CREATE TABLE Usuarios (
    usuario_id NUMBER CONSTRAINT pk_usuarios PRIMARY KEY,
    nome VARCHAR2(100) CONSTRAINT nn_nome_usuario NOT NULL,
    setor_id NUMBER,
    nivel NUMBER DEFAULT 1,
    CONSTRAINT fk_setor_usuario FOREIGN KEY (setor_id) REFERENCES Setores(setor_id) ON DELETE CASCADE
);


CREATE TABLE Arquivos (
    Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- Chave primária com incremento automático
    NomeArquivo VARCHAR2(255) NOT NULL,                              -- Nome do arquivo
    TipoArquivo VARCHAR2(50),                                        -- Tipo do arquivo (por exemplo, .pdf, .jpg)
    TamanhoArquivo NUMBER,                                           -- Tamanho do arquivo em bytes
    Conteudo BLOB,                                                   -- Conteúdo do arquivo em formato binário (BLOB)
    DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- Data de criação com valor padrão de data e hora atual
);

SELECT * FROM usuarios;